"""
This type stub file was generated by pyright.
"""

import base64
import mimetypes
import os
import datetime
import re
import copy
import warnings
from email.mime.audio import MIMEAudio
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email import encoders
from googleapiclient.discovery import build
from httplib2 import Http
from oauth2client import client, file, tools

"""EZGmail - A Pythonic interface to the Gmail API that actually works as of October 2022."""
__version__ = ...
SCOPES = ...
SERVICE_GMAIL = ...
EMAIL_ADDRESS: str = ...
LOGGED_IN = ...
class EZGmailException(Exception):
    """The base class for all EZGmail-specific problems. If the ``ezgmail`` module raises something that isn't this or
    a subclass of this exception, you can assume it is caused by a bug in EZGmail."""
    ...


class EZGmailValueError(EZGmailException):
    """The EZGmail module equivalent of ValueError. This exception is raised when a parameter of an incorrect value
    (but not necessarily an incorrect type) is passed to an EZGmail function."""
    ...


class EZGmailTypeError(EZGmailException):
    """The EZGmail module equivalent of ValueError. This exception is raised when a parameter of an incorrect type
    is passed to an EZGmail function."""
    ...


class GmailThread:
    """Represents a thread of Gmail messages. These objects are returned by the users.threads.get() API call. They
    contain references to a list of GmailMessage objects."""
    def __init__(self, threadObj) -> None:
        ...
    
    @property
    def text(self): # -> list[Any]:
        """A list of strings, where each string is the message of a single email in this thread of emails, starting
        from the oldest at index 0 to the most recent."""
        ...
    
    @property
    def messages(self) -> list[GmailMessage]: # -> list[Any]:
        """The GmailMessage objects of the emails in this thread, starting from the oldest at index 0 to the most
        recent."""
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def senders(self): # -> list[Any]:
        """Returns a list of strings of the senders in this thread, from the oldest at index 0 to the most recent."""
        ...
    
    def latestTimestamp(self):
        """The """
        ...
    
    def addLabel(self, label): # -> None:
        """Add the label ``label`` to every message in this thread."""
        ...
    
    def removeLabel(self, label): # -> None:
        """Remove the label ``label`` from every message in this thread, if it's there."""
        ...
    
    def markAsRead(self) -> None:
        """Mark every message in this thread as read. (This does the same thing as removing the UNREAD label from the
        messages.)"""
        ...
    
    def markAsUnread(self): # -> None:
        """Mark every message in this thread as unread. (This does the same thing as adding the UNREAD label to the
        messages.)"""
        ...
    
    def trash(self): # -> None:
        """Move every message in this thread to the Trash folder. It will be automatically removed in 30 days."""
        ...
    


def removeQuotedParts(emailText):
    """Returns the text in ``emailText`` up to the quoted "reply" text that begins with
    "On Sun, Jan 1, 2018 at 12:00 PM al@inventwithpython.com wrote:" part."""
    ...

class GmailMessage:
    """Represents a Gmail messages. These objects are returned by the users.messages.get() API call. They contain all the header/subject/body information of a single email.

    The ``sender`` attribute has a string like ``'Google <no-reply@accounts.google.com>'``.

    The ``recipient`` attribute has a string like ``al@inventwithpython.com'``.

    The ``subject`` attribute contains a string of the subject line.

    The ``body`` attribute contains text up to the quoted "reply" text that begins with
    "On Sun, Jan 1, 2018 at 12:00 PM al@inventwithpython.com wrote:" part.

    The ``originalBody`` attribute contains the full message body.

    The ``timestamp`` attribute contains a ``datetime.datetime`` object of the internal message creation timestamp (epoch
    ms), which determines ordering in the inbox.

    The ``snippet`` attribute contains a string of up to the first 200 characters of the body.

    These attributes are based on the Gmail API: https://developers.google.com/gmail/api/v1/reference/users/messages
    """
    sender: str
    recipient: str
    timestamp: datetime.datetime
    subject: str
    snippet: str
    body: str
    id: str
    threadId: str
    attachments: list[str]


    def __init__(self, messageObj) -> None:
        """Create a GmailMessage object. The ``messageObj`` is the dictionary returned by the ``users.messages.get()`` API
        call."""
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __str__(self) -> str:
        ...
    
    def senders(self) -> list[str]: # -> list[Any]:
        ...
    
    def latestTimestamp(self): # -> datetime:
        ...
    
    def downloadAttachment(self, filename, downloadFolder=..., duplicateIndex=...): # -> None:
        """Download the file attachment in this message with the name ``filename`` to the local folder ``downloadFolder``.
        If there are multiple attachments with the same name, ``duplicateIndex`` needs to be passed to specify
        which attachment to download."""
        ...
    
    def downloadAllAttachments(self, downloadFolder=..., overwrite=...): # -> list[Any]:
        """Download all of the attachments in this message to the local folder ``downloadFolder``. If ``overwrite`` is
        ``True``, existing local files will be overwritten by attachments with the same filename."""
        ...
    
    def addLabel(self, label): # -> None:
        """Add the label ``label`` to every message in this thread."""
        ...
    
    def removeLabel(self, label): # -> None:
        """Remove the label ``label`` from every message in this thread, if it's there."""
        ...
    
    def markAsRead(self) -> None:
        """Mark this message as read. (This does the same thing as removing the UNREAD label from the message.)"""
        ...
    
    def markAsUnread(self): # -> None:
        """Mark this message as unread. (This does the same thing as adding the UNREAD label to the message.)"""
        ...
    
    def trash(self): # -> None:
        """Move this message to the Trash folder. It will be automatically removed in 30 days."""
        ...
    
    def reply(self, body, attachments=..., cc=..., bcc=..., mimeSubtype=...): # -> None:
        """Like the send() function, but replies to the last message in this thread."""
        ...
    
    def replyAll(self, body, attachments=..., cc=..., bcc=..., mimeSubtype=...): # -> None:
        """Like the send() function, but replies to the last message in this thread."""
        ...
    


def init(userId=..., tokenFile=..., credentialsFile=..., _raiseException=...) -> bool:
    """This function must be called before any other function in EZGmail (and is automatically called by them anyway,
    so you don't have to explicitly call this yourself).

    This function populates the ``SERVICE_GMAIL`` global variable used in all Gmail API calls. It also populates
    ``EMAIL_ADDRESS`` with a string of the Gmail account's email address (and sets the global ``LOGGED_IN`` to ``True``). This account is determined by the *credentials.json* file, downloaded from Google, and *token.json*. If the ``tokenFile``
    file hasn't been generated yet, this function will open the browser to a page to let the user log in to the Gmail account that this module will use.

    If you want to switch to a different Gmail account, call this function again with a different ``tokenFile`` and
    ``credentialsFile`` arguments.
    """
    ...

def send(recipient, subject, body, attachments=..., sender=..., cc=..., bcc=..., mimeSubtype=..., _threadId=...): # -> None:
    """Sends an email from the configured Gmail account.

    Note that the ``sender`` argument seems to be ignored by Gmail, which uses the account's actual email address.

    TODO - Add additional details to this docstring."""
    ...

def search(query: str, maxResults: int | None =..., userId=...) -> list[GmailThread]:
    """Returns a list of GmailThread objects that match the search query.

    The ``query`` string is exactly the same as you would type in the Gmail search box, and you can use the search
    operatives for it too:

        * label:UNREAD
        * from:al@inventwithpython.com
        * subject:hello
        * has:attachment

    More are described at https://support.google.com/mail/answer/7190?hl=en
    """
    ...

def recent(maxResults=..., userId=...): # -> list[GmailThread]:
    """Return a list of ``GmailThread`` objects for the most recent emails. Essentially a wrapper for ``search()``.

    First index is the most recent."""
    ...

def unread(maxResults=..., userId=...): # -> list[GmailThread]:
    """Return a list of ``GmailThread`` objects for unread emails. Essentially a wrapper for ``search()``."""
    ...

def summary(gmailObjects, printInfo=...): # -> list[Any] | None:
    """Prints out a summary of the ``GmailThread`` or ``GmailMessage`` in the ``gmailObjects`` list."""
    ...

def removeLabel(*args, **kwargs): # -> None:
    ...

def addLabel(*args, **kwargs): # -> None:
    ...

def markAsRead(*args, **kwargs) -> None:
    ...

def markAsUnread(*args, **kwargs): # -> None:
    ...

